name: Daily Check-in

on:
  schedule:
    - cron: "0 13 * * *"  # Runs every day at 6 AM UTC (adjust as needed)
  workflow_dispatch:

jobs:
  create-daily-checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up date
        run: echo "DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Copy Daily Template
        run: |
          mkdir -p checkins
          cp DAILY_CHECKIN_TEMPLATE.md checkins/${{ env.DATE }}.md

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add checkins/${{ env.DATE }}.md
          git commit -m "📝 Add daily check-in for ${{ env.DATE }}"
          git push

