name: Daily Check-in

on:
  schedule:
    - cron: "0 13 * * *"  # Runs every day at 6 AM UTC (adjust as needed)
  workflow_dispatch:

jobs:
  create-daily-checkin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up date
        run: echo "DATE=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Copy Daily Template
        run: |
          mkdir -p checkins
          if [ ! -f "checkins/${{ env.DATE }}.md" ]; then
            cp DAILY_CHECKIN_TEMPLATE.md checkins/${{ env.DATE }}.md
            echo "CREATED_FILE=true" >> $GITHUB_ENV
          else
            echo "CREATED_FILE=false" >> $GITHUB_ENV
            echo "Daily check-in file for ${{ env.DATE }} already exists"
          fi

      - name: Commit and push
        if: env.CREATED_FILE == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add checkins/${{ env.DATE }}.md
          git commit -m "📝 Add daily check-in for ${{ env.DATE }}"
          git push

